# GLOBAL CONFIGURATION
global:
  #SET SCRAPE AND EVALUATE INTERVAL TO 30SECS
  scrape_interval:     30s 
  evaluation_interval: 30s 
  
  external_labels:
      monitor: 'codelab-monitor'


rule_files:

scrape_configs:
  
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'csvserver'

    static_configs:
      - targets: ['localhost:9393']
